// Dependencies
import Head from 'next/head'
import { getFeaturedEvents } from '../data/dummy-data'

// Components
import EventList from '../components/events/EventList'

export default function HomePage() {
  const featuredEvents = getFeaturedEvents()

  return (
    <div>
      <Head>
        <title>Next Event App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EventList items={featuredEvents} />
    </div>
  )
}
